### ISSUE TITLE
Stuck after PogoDroid installation.

### ISSUE THREAD

**Issue by Meowthkes** [Map-A-Droid/MAD-ATV#101]
Seems to be the same issue as #79 .

Used SD card method to install MAD-ATV 1.2.0 on an x96 Mini. After finishing setup and entering the App Drawer, nothing is there. After a few seconds, PogoDroid appears as well. Then it stops, however, and nothing else is installed.

I've tried rebooting, leaving it online for a whole night, manually entering TWRP and moving to next to the router, but nothing seems to work.

Earlier, I had installed a previous version (I think it was 1.1.0) and the same occurred. I read that 1.2.0 should have fixed that, but it didn't.

Is there any way to continue manually? Should I try with an older version?

**Comment by krzee** [comment]
discord for support, not here.
see the pinned post in the atv help channel
