### ISSUE TITLE
64 bit rom - Request to show the IP Assigned when the autoconf process is complete.

### ISSUE THREAD

**Issue by CarlosVMX1** [Map-A-Droid/MAD-ATV#103]
Reflashed some A95x F1 boxes with the 64bits beta5 rom and the IP they had assigned with the 32bits version changed, so would be good if we can get the new IP assigned to the box at the MADmin autoconf log  when the process is complete so we can grab it and reconfigure our adb access. thanks!

**Comment by krzee** [comment]
1) You could run the info job which does exactly that

2) If you updated 32bit before upgrading you should end up using the same mac address, and if you configured the IPs in your router like you should, then you should end up getting the same old IP after second boot (assuming you used autoconfig).

3) There is a feature request for madmin to put public IP and lan IP next to eachother in autoconfig sessions

For these 3 reasons Im closing this
