### ISSUE TITLE
[Feature-Request] include a SSH client that create portforwardings for ADB to a configured on demand

### ISSUE THREAD

**Issue by philcerf** [Map-A-Droid/MAD-ATV#107]
Hi.

Often, the ATV devices are hosted at some people from the community behind their routers.

When problems arise, it's handy to have ADB/scrcpy connection but this requires a port forwarding at the side of the hoster, which is not only insecure, but also difficult to get.

It would be nice, if the ATV image could include the necessary programs so that one could run a job that lets a SSH client on the device create the necessary portforwardings to the MAD server (or some other server).

Ideally one could configure the server's public key at the MAD server (which is then automatically exchanged) and would also get the clients (automatically generated) public key.
Obviously one would also need to be able to configure some username and ports (i.e. for ssh itself **and** for the binding of the forward).

Cheers!

**Comment by Expl0dingBanana** [comment]
I don't think this will ever get implemented. If you want to do this you should look into a VPN to connect your atvs to the same network

**Comment by krzee** [comment]
what he said ☝️
or you could implement what you said via another script of your own. it could be an init script which you install via a job.
