### ISSUE TITLE
Improvement: fetch init and autoconfig scripts from github

### ISSUE THREAD

**Issue by fosJoddie** [Map-A-Droid/MAD-ATV#16]
To allow for script updates without reflashing, make the a primary script download the (secondary/payload) script from this github repo

**Comment by krzee** [comment]
this is now done.
update_mad.sh has the -i flag to update the init script.
the init script checks the version on update_mad.sh and updates it on boot if necessary.

of course for loading this without a new release (yet) theres a chicken or egg problem
youd have to load 1 by hand (or madmin job), either one
if you update update_mad.sh then you can run update_mad -i to update the init script
if you update the init script, it'll check the update_mad.sh version on boot and update it if its not the version specified in the init script

thank you for putting this here :)
and thank you to coldshadow for the idea to use update_mad.sh
