### ISSUE TITLE
Improvement: Auto update PoGo app on ATVs if installed apk below forced version

### ISSUE THREAD

**Issue by ColdShadow80** [Map-A-Droid/MAD-ATV#24]
Add a daily PoGo app version routine on ATV's to compare current version against forced version and flash update if device version is below forced version number.

_Idea derived from original text"...compare force version against local pogo version and flash update on the screen
although i guess we could make a script that does that 1x per day and just updates when needed :scream: ..."_

**Comment by dkmur** [comment]
Why wait for forced update? Device could be down for up to almost a day before being updated.
Consider daily check against addresses.json, when added, just update device.

**Comment by C64Axel** [comment]
But please make this switchable

**Comment by ColdShadow80** [comment]
> Why wait for forced update? Device could be down for up to almost a day before being updated.
> Consider daily check against addresses.json, when added, just update device.

True. Not sure if somewone can bash script it against adresses.json but if it could, then it would make sence to check against  addresses.json releases on Github. That way all ATVs would be updated in the next 24h after a release of adresses in MAD repo.

**Comment by krzee** [comment]
Should be doable. Pogodroid only knows where to get addresses.json if it's properly configured so I can get that info from the config file like it does. I can check what version of pogo I'm downloading similar to how I download the apk. I can compare and update only if the servers addresses.json supports it.
And it's trivial to add an option for users to disable this.

**Comment by krzee** [comment]
Well you're right it has fallback to GitHub too, but I prefer using the servers copy

**Comment by krzee** [comment]
storing this here for myself:

`pserver=$(grep post_destination /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|grep -v raw|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')`
`user=$(grep auth_username /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')`
`pass=$(grep auth_password /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')`
`origin=$(grep post_origin /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')`

`installedver=$(dumpsys package com.nianticlabs.pokemongo|grep versionName|awk -F'=' '{print $2}')`
`addressfile=$(curl -H "origin: $origin" -u "$user:$pass" "$pserver/get_addresses/")` 
`newver=$(curl -k -s "https://m.apkpure.com$(curl -k -s 'https://m.apkpure.com/pokemon-go/com.nianticlabs.pokemongo/versions'|awk -F'"' '/Download/'|grep 'mon GO v'|awk -F'"' '{print $4}'|head -n1)"|grep -A10 armeabi-v7a|awk '/Download Pok/{print $5}'|head -n1|sed 's,v,,')`

**Comment by krzee** [comment]
update_pogo(){
[[ -f /sdcard/disableautopogoupdate ]] && return 0
newver="$(curl -k -s "https://m.apkpure.com$(curl -k -s 'https://m.apkpure.com/pokemon-go/com.nianticlabs.pokemongo/versions'|awk -F'"' '/Download/'|grep 'mon GO v'|awk -F'"' '{print $4}'|head -n1)"|grep -A10 armeabi-v7a|awk '/Download Pok/{print $5}'|head -n1|sed 's,v,,')"
installedver="$(dumpsys package com.nianticlabs.pokemongo|grep versionName|awk -F'=' '{print $2}')"
[[ "$newver" == "$installedver" ]] && return 0

pserver=$(grep post_destination /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|grep -v raw|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')
user=$(grep auth_username /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')
pass=$(grep auth_password /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')
origin=$(grep post_origin /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|awk -F'>' '{print $2}'|awk -F'<' '{print $1}')

if [[ "$user" == "" ]] ;then
  if curl -H "origin: $origin" "$pserver/get_addresses/"| grep -q "${newver}_32" ;then
    /system/bin/update_mad.sh -p
  fi
else
  if curl -H "origin: $origin" -u "$user:$pass" "$pserver/get_addresses/"| grep -q "${newver}_32" ;then
   /system/bin/update_mad.sh -p
  fi
fi
}

update_pogo

**Comment by krzee** [comment]
any thoughts on the above?

**Comment by krzee** [comment]
merged
create /sdcard/disableautopogoupdate to disable this
