### ISSUE TITLE
Power cable during flash

### ISSUE THREAD

**Issue by svenberg** [Map-A-Droid/MAD-ATV#33]
"When the box is seen in the burn tool it will start flashing. Connect the power cable"
Apparently the power cord is not needed when flashing ATVs
This has been true for all of my a95xf1 boxes so far

**Comment by svenberg** [comment]
This is for README_usbflashing.md

**Comment by dkmur** [comment]
I agree there seems to be no need to do that, flashed some 30 A95xF1s never use power cable

**Comment by krzee** [comment]
it gets rid of LOWPOW errors and warnings, which also gets rid of the questions about that.
