### ISSUE TITLE
a95xf1 reset button not needed

### ISSUE THREAD

**Issue by svenberg** [Map-A-Droid/MAD-ATV#36]
From README_usbflashing.md
The reset button is not needed when flashing a95xf1
Follow the instructions of USB burning tool, click start, plug the usb in the right side port and it will start flashing immediately

**Comment by krzee** [comment]
ya i know, but the install directions work for EVERY device mad rom supports, and this is a 1-off exception. i guess if you want to submit device specific notes into the readme file as PR's i could accept it, but i feel like it'll lead to more confusion / questions than it would solve.
