### ISSUE TITLE
Auto-Configure hostname to allow user-friendly DHCP registration

### ISSUE THREAD

**Issue by Expl0dingBanana** [Map-A-Droid/MAD-ATV#48]
mount -o rw,remount /system
origin="$(awk -F'>' '/post_origin/{print $2}' /data/data/com.mad.pogodroid/shared_prefs/com.mad.pogodroid_preferences.xml|cut -d'<' -f1)"
echo "net.hostname=${origin}" >> /system/build.prop
mount -o ro,remount /system
reboot

**Comment by krzee** [comment]
update_mad.sh -n
