### ISSUE TITLE
Download of the releases ist incredibly slow

### ISSUE THREAD

**Issue by TheEnjinia** [Map-A-Droid/MAD-ATV#53]
This may be out of scope, but I am having trouble downloading the releases here on Github. 

- I have a 125 Mbit connection
- ISP router has been restarted
- I already tried different browsers and different machines
- Other web services (Gaming, VoD Streaming, VoIP) work flawlessly

Stil when I try to download a release, it reduces speed down to 10 kbs

What might be the problem?

**Comment by muckelba** [comment]
!blame github CDN :D Thats nothing we can improve unfortunately. One workaround is to download the file to a different device (maybe your server). That fixed those issues for me.

**Comment by Audidriver13** [comment]
Quick tip:  you can use a download helper/tool to load the file with multiple connections
