### ISSUE TITLE
unable to install NFS via nfs_install.sh

### ISSUE THREAD

**Issue by dkmur** [Map-A-Droid/MAD-ATV#56]
atvX_s905w:/system/bin # sh -x nfs_install.sh
+ $'\r'
: not found.sh[4]:
+ mkdir -p $'/cache/recovery\r'
+ touch $'/cache/recovery/command\r'
+ >>$'/cache/recovery/command\r'
+ echo '--update_package=/sdcard/NFS-INJECTOR.zip'
+ >>$'/cache/recovery/command\r'
+ echo --wipe_cache
+ reboot $'recovery\r'

**Comment by dkmur** [comment]
krzee said it's dos line endings :P

**Comment by krzee** [comment]
is this fixed?

**Comment by ColdShadow80** [comment]
Update nfs_install.sh #57 was just merged. 
It is meant to fix it. 
The PR was tested sucessfully on several devices before merged.

**Comment by krzee** [comment]
@dkmur can you confirm its better for you?

**Comment by dkmur** [comment]
been using a job based on what Coldshadow cooked up, no problems during install and nfs is running fine on all new devices, so yes it works.
