### ISSUE TITLE
not able to use Remote

### ISSUE THREAD

**Issue by Laemmamen** [Map-A-Droid/MAD-ATV#61]
hi i descriped my issue nearer here

https://github.com/Map-A-Droid/MAD-device-list/issues/34

Yagala YA-II | S905W | MAD rom | 18.1 | Yes | SD card (USB A to USB A untested) | ~20 min. | Only tried on one device! ROM and procedure exactly the same as X96 Mini
-- | -- | -- | -- | -- | -- | -- | --

i hav installen now the MAD-ATV but remote is workin any more

**Comment by acocalypso** [comment]
because the remote driver are not in the rom as its not needed.

**Comment by bbdoc** [comment]
How do you connect to a wifi network without a remote ? You cannot connect to adb until you have an IP assigned... I have installed several devices and remote has always been working.

**Comment by ColdShadow80** [comment]
Probably device related. Are all your atvs Yagala? 
As for connection, USB keyboard and mouse should be enough to bypass that bug.

**Comment by krzee** [comment]
remote is not necessary for scanners. maybe some work, maybe not.
