### ISSUE TITLE
set PD and RGC magisk permissions during first install

### ISSUE THREAD

**Issue by ColdShadow80** [Map-A-Droid/MAD-ATV#63]
example code:

uid=$(dumpsys package com.mad.pogodroid | grep userId= | awk -F '=' '{print $2}')
sqlite3 /data/adb/magisk.db "DELETE from policies WHERE package_name='com.mad.pogodroid'"
sqlite3 /data/adb/magisk.db "INSERT INTO policies (uid,package_name,policy,until,logging,notification) VALUES(\""$uid"\",'com.mad.pogodroid',2,0,1,1)"

**Comment by bbdoc** [comment]
Good idea.

What about also repackaging magisk ? Is it possible ?

**Comment by krzee** [comment]
Sure, just find how and I'll implement it. I don't know of a way, but to be
fair I didn't know about this before coldshadow told me.

**Comment by dkmur** [comment]
Consider adding shell too

**Comment by krzee** [comment]
no problem, especially if somebody leaves the commands here for shell and RGC.
please test them first!
that way when im digging in for a rewrite its less stuff ill need to work on / test. if you guys say it worked for you ill just add it and test it together with the rest

**Comment by ColdShadow80** [comment]
RGC should be as simple as replicating the PD code and switch the apk name and folder on the previous example. 
I will try to cook up something for Shell access too, have to think about how to get the right ID. 

Still do not know any way to make repackaging, to be fair air have not found a way to interact with any Magisk Manager prefence using shell, other than turning modules ON or OFF so if anyone can provide any info on that it would be appreciated

**Comment by JabLuszko** [comment]
I guess those "permissions" is allowing root access? Maybe it will be easier to just set it to "allow" for everything rather than enabling few selected apps? This is ATV image, we are not going to run anything else here.

**Comment by krzee** [comment]
^ that's what i've always done, so i do agree. but since some people seem to care and its just a couple commands, may as well just automate those 3 things and let people change it to allow all if they want to

**Comment by krzee** [comment]
this would have been added today if anybody left me all the commands

**Comment by krzee** [comment]
hah i guess it got added today anyways. thanks for the nudge in the right direction
