### ISSUE TITLE
Stop killing RGC in update_mad.sh

### ISSUE THREAD

**Issue by TechG3n** [Map-A-Droid/MAD-ATV#64]
Don't update RGC as first step in the -a update part.
Or just don't kill it at all if we can just update it.

At the moment a job with -a will Fail because rgc will lose the conenction.

**Comment by krzee** [comment]
thanks for making this note for me, we'll change this behavior in  the upcoming rewrite

**Comment by krzee** [comment]
fixed this awhile back
