### ISSUE TITLE
Linux solution for USB flashing needed

### ISSUE THREAD

**Issue by jinnatar** [Map-A-Droid/MAD-ATV#66]
While the SD method works for first install, it does not work after the MAD rom is installed. The USB installer is windows only and does not run under wine.

SD install apparently continues to work for x96 but not with the f1.

**Comment by jinnatar** [comment]
Alternatively, enable SD flashing to continue for more models.

**Comment by fosJoddie** [comment]
I know it's not automatic, but I'm pretty sure you can flash an img file directly from TWRP (which is btw why SD card flashing do not work once you've done it once)

**Comment by krzee** [comment]
are you saying you have a linux usb flashing solution, or that you want one?
even if i had one i wouldnt want to support it lol
you can reflash your f1 via SD if you go back to stock recovery first
we dont really invent new flashing methods, but i wish you good luck

**Comment by krzee** [comment]
i dont know or care if this will work, and dont come to me for help with it.
https://github.com/Stane1983/aml-linux-usb-burn
