### ISSUE TITLE
M8S MAX flashing failed

### ISSUE THREAD

**Issue by memc0re** [Map-A-Droid/MAD-ATV#75]
I have tried to flash an MECOOL M8S Max, but is failed.
Flashing an original firmware "M8S_Max_20190605.164225.V0213.img" works fine.
I used "MAD-s912-1.2.0.img" and USB_Burning_Tool V2.1.7.0

[18:19:40 203][HUB3-4][Inf]--Start burning...
[18:19:40 265][HUB3-4][Inf]--------------ERASE BOOTLOADER------------
[18:19:40 373][HUB3-4][Inf]--start SendIdentifyCmd
[18:19:40 374][HUB3-4][Inf]--2-2-0-0
[18:19:40 374][HUB3-4][Inf]-------------Download DDR.USB-----------
[18:19:40 374][HUB3-4][Inf]--2-2-0-0
[18:19:40 374][HUB3-4][Inf]--Control write pll reg1 0xd9000000:0x000000b1
[18:19:40 884][HUB3-4][Inf]--Control write pll reg1 0xd9000000:0x00005183
[18:19:41 394][HUB3-4][Inf]--Control write pll reg1 0xd9000000:0x000000b1
[18:19:41 905][HUB3-4][Inf]--Control write pll reg1 0xd9000000:0x00005183
[18:19:42 415][HUB3-4][Inf]--Write initial succeed
[18:19:42 415][HUB3-4][Inf]--Upload encrypt at 0xc8100228
[18:19:42 416][HUB3-4][Inf]--ulValue = 0xadfc318c
[18:19:42 416][HUB3-4][Inf]--Read encrypt value succeed
[18:19:42 416][HUB3-4][Inf]--Download DDR.USB,size: 49152!
[18:19:42 427][HUB3-4][Inf]--Transfer complete 49152
[18:19:42 427][HUB3-4][Inf]--Run at address 0xd9000000
[18:19:42 428][HUB3-4][Inf]--RunInRam success
[18:19:42 793][HUB3-4][Inf]--IOCTL_IDENTIFY_HOST_Handler ret=-5 error_msg=libusb0-dll:err [control_msg] sending control message failed, win error: A device connected to the system is not working.
[18:19:42 800][HUB3-4][Err]--[0x10105004]Romcode/Initialize DDR/Read initialize status/Error result
[18:19:42 801][HUB3-4][Inf]--Close device handle 0x000008e8

**Comment by ColdShadow80** [comment]
wiki says "...S912 rom is brand new and has basically no testing. Only known to work on 2gb/8gb tx9s, no information about units it does not work on..."

**Comment by memc0re** [comment]
> 
> 
> wiki says "...S912 rom is brand new and has basically no testing. Only known to work on 2gb/8gb tx9s, no information about units it does not work on..."

I know, but it is also a feedback. And can test/try everything on my device. If i brick the device, it doesn't matter.

**Comment by memc0re** [comment]
Now i have tried all atvXperience V2H with the same error.
And now i have succeced burned the image named "s912_LPDDR_atvXperience_v2FF.img".
It works very fast, IR-Remote-Control & PowerLED works also. 
atvXperience show 3GB RAM & 32GB Flash.

**Comment by Grennith** [comment]
Sorta offtopic: Does the M8S Max have a reset button or how do you enter flashing mode? Got some M8S Pro LB lying around which I haven't gotten around to flash yet. It lacks a proper flash mode I think

**Comment by memc0re** [comment]
> 
> 
> Sorta offtopic: Does the M8S Max have a reset button or how do you enter flashing mode? Got some M8S Pro LB lying around which I haven't gotten around to flash yet. It lacks a proper flash mode I think

On my Board is no Reset-Button fitted, i have used the "Menu"-Button on the IR-Remote Control.
https://www.youtube.com/watch?v=45IIjk-UXTw

**Comment by krzee** [comment]
well thats a new method to me! thanks!

**Comment by krzee** [comment]
also, ya i knew my s912 rom wouldnt work on lpddr
https://discordapp.com/channels/465247740553592832/590787129458688000/691690255924854894

i know i can make one, i just dont have one of those boxes to test on

**Comment by memc0re** [comment]
Thanks @krzee , i have seen the new Image and i will test it on my device.
BTW: Discordlink not working for memcore#4197

**Comment by memc0re** [comment]
Flashing works, whithout Problem on M8S MAX.
("Menu"-Button on the IR-Remote Control method  used)

- but not eth0 (in "s912_LPDDR_atvXperience_v2FF.img"also no eth0), but Wifi works.
- MAD-Bootlogo was shown, IR Remote works, System looks good.
- but no restart in recovery after first boot
- update_mad.sh works but nothing is installed ("apk-files" are in Downloads directory):
> atvX_S912LP:/system/bin # update_mad.sh -a
> 
> updating RGC...
> Delete old APK RGC
> Download APK RGC
> Install APK RGC
> Success
> 
> updating PogoDroid...
> Delete old APK PogoDroid
> Download APK PogoDroid
> Install APK PogoDroid
> Success
> 
> updating PokemonGo...
> Delete old APK PokemonGo
> Download APK PokemonGo
> Install APK PokemonGo
> Success
> 
> updating init scripts...
> 
> atvX_S912LP:/system/bin # 

- nfs_install.sh:
> atvX_S912LP:/system/bin # nfs_install.sh
> /sdcard/NFS-INJECTOR.zip does not exist
> 1|atvX_S912LP:/system/bin #

**Comment by ColdShadow80** [comment]
update_mad.sh downloads the new version of the apks from internet before install, any version still on the box is removed by the script.
Did you had internet access on the box when you ran the script?

Steps are usually:
1. Delete old downloaded version
2. Download new version
3. Install new (downloaded) version

example:
function update_rgc(){
	echo "updating RGC..."
	echo "Delete old APK RGC"
	/system/bin/rm -f /sdcard/Download/RemoteGpsController.apk
	echo "Download APK RGC"
	cd /sdcard/Download/
	/system/bin/curl -L -o RemoteGpsController.apk -k -s https://raw.githubusercontent.com/Map-A-Droid/MAD/master/APK/RemoteGpsController.apk
	echo "Install APK RGC"
	/system/bin/pm install -r /sdcard/Download/RemoteGpsController.apk
	echo
}

**Comment by krzee** [comment]
> > atvX_S912LP:/system/bin # nfs_install.sh
> > /sdcard/NFS-INJECTOR.zip does not exist
> > 1|atvX_S912LP:/system/bin #

i do not maintain that script, nor do i condone using nfs. fix it and submit via PR if you care

**Comment by krzee** [comment]
>     * but no restart in recovery after first boot
> 
>     * update_mad.sh works but nothing is installed ("apk-files" are in Downloads directory):

This is probably my fault, i packaged a bad 16mad with windows line endings. if you redownload the lpddr package it should be better

**Comment by dkmur** [comment]
> > > atvX_S912LP:/system/bin # nfs_install.sh
> > > /sdcard/NFS-INJECTOR.zip does not exist
> > > 1|atvX_S912LP:/system/bin #
> 
> i do not maintain that script, nor do i condone using nfs. fix it and submit via PR if you care

had the same on A95x F1, seems the zip file is not being downloaded

**Comment by JabLuszko** [comment]
https://discordapp.com/channels/465247740553592832/590787129458688000/701567344861904917 for working TWRP and next message for (probably) working LAN. M8S MAX seems to be using the same LAN as M8S PRO L LB

**Comment by krzee** [comment]
not going to work on lpddr version unless somebody would like to send me one. i dont want to support different models that i dont have to test with.

**Comment by memc0re** [comment]
> 
> 
> not going to work on lpddr version unless somebody would like to send me one. i dont want to support different models that i dont have to test with.

If you are living in EU, i will send you my M8S MAX.

**Comment by krzee** [comment]
it would be USA

**Comment by memc0re** [comment]
> 
> 
> it would be USA

Sorry, USA is too far. The Shipping cost are too expensive.
